// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Pfim")]
[assembly: AssemblyProductAttribute("Pfim")]
[assembly: AssemblyDescriptionAttribute("Image file format parser")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
