// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Pfim")]
[assembly: AssemblyProductAttribute("Pfim")]
[assembly: AssemblyDescriptionAttribute("Image file format parser")]
[assembly: AssemblyVersionAttribute("0.3")]
[assembly: AssemblyFileVersionAttribute("0.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.3";
    }
}
